### ISSUE TITLE
Retry URI query

### ISSUE THREAD

**Issue by shorsher** [hyperledger/firefly-tokens-erc1155#114]
If there is ever a transient error when querying for a token URI, the connector will return an empty string. We should add a retry mechanism and better logging to try to  prevent scenarios where uri's are incorrectly returned to FireFly. 

https://github.com/hyperledger/firefly-tokens-erc1155/blob/206aab4e0a6834c43ff9122b8b5b047e174ae058/src/tokens/tokens.listener.ts#L330

**Comment by awrichar** [comment]
This same problem exists for ERC721:
https://github.com/hyperledger/firefly-tokens-erc20-erc721/blob/8d7f695a51b37ab47297a281afd59457f175a918/src/tokens/tokens.listener.ts#L95
