### ISSUE TITLE
Add tests for solidity token contracts

### ISSUE THREAD

**Issue by panghalamit** [hyperledger/firefly-tokens-erc1155#13]
We might want to add tests for the erc1155 contract. These could be an extension  of tests at https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/test/token/ERC1155/ERC1155.test.js

**Comment by awrichar** [comment]
Should follow the pattern from the [erc20_erc721 connector](https://github.com/hyperledger/firefly-tokens-erc20-erc721/tree/main/samples/solidity/test).
